### ISSUE TITLE
Missing file of ` /content/generate_tf_records.py`

### ISSUE THREAD

**Issue by JL1829** [Deshram/Road-Damage-Detection#1]
Hi: 

Can I have the ` /content/generate_tf_records.py` file in your notebook?

**Comment by Deshram** [comment]
I think you'll get all those scripts when you clone tensorflow object detecion 

You can refer from [here](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html#create-tensorflow-records)
